export const ActionTypes = {
    SET_NEXT_SLIDER : "SET_NEXT_SLIDER",
    SET_PREV_SLIDER : "SET_PREV_SLIDER",
    SET_DOT_SLIDER : "SET_DOT_SLIDER",
    ASSIGN_PRODUCT : "ASSIGN_PRODUCT",
    ASSIGN_PRODUCTS : "ASSIGN_PRODUCTS",
}