export const ActionTypes = {
    SET_NEXT_SLIDER : "SET_NEXT_SLIDER",
    SET_PREV_SLIDER : "SET_PREV_SLIDER",
    SET_DOT_SLIDER : "SET_DOT_SLIDER",
    ASSIGN_PRODUCT : "ASSIGN_PRODUCT",
    ASSIGN_PRODUCTS : "ASSIGN_PRODUCTS",
    FILTER_GENDER : "FILTER_GENDER",
    SORT_PRICE : "SORT_PRICE",
    DISP_SIZE : "DISP_SIZE",
    DISP_COLOR : "DISP_COLOR",
    ASSIGN_CART : "ASSIGN_CART",
    REMOVE_PRODUCT : "REMOVE_PRODUCT",
    ADD_SALES_PRODUCT : "ADD_SALES_PRODUCT"
}